version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-snippetbox
    restart: 'no'
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: web
      MYSQL_PASSWORD: dev
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_bin"

